/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public class AIBase {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AIBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AIBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AIBase obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fastfizJNI.delete_AIBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GameShot computeShot(GameState gs, Noise noise) {
    return new GameShot(fastfizJNI.AIBase_computeShot__SWIG_0(swigCPtr, this, GameState.getCPtr(gs), gs, Noise.getCPtr(noise), noise), false);
  }

  public GameShot computeShot(GameState gs) {
    return new GameShot(fastfizJNI.AIBase_computeShot__SWIG_1(swigCPtr, this, GameState.getCPtr(gs), gs), false);
  }

  public GameShot reComputeShot() {
    return new GameShot(fastfizJNI.AIBase_reComputeShot(swigCPtr, this), false);
  }

  public boolean forGame(GameType gt) {
    return fastfizJNI.AIBase_forGame(swigCPtr, this, gt.swigValue());
  }

}
