/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public class CueStrikeEvent extends Event {
  private transient long swigCPtr;

  protected CueStrikeEvent(long cPtr, boolean cMemoryOwn) {
    super(fastfizJNI.CueStrikeEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CueStrikeEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CueStrikeEvent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fastfizJNI.delete_CueStrikeEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CueStrikeEvent(ShotParams params) {
    this(fastfizJNI.new_CueStrikeEvent__SWIG_0(ShotParams.getCPtr(params), params), true);
  }

  public CueStrikeEvent(double time, ShotParams params) {
    this(fastfizJNI.new_CueStrikeEvent__SWIG_1(time, ShotParams.getCPtr(params), params), true);
  }

  public CueStrikeEvent(double time, SWIGTYPE_p_Pool__Ball__Type b, ShotParams params) {
    this(fastfizJNI.new_CueStrikeEvent__SWIG_2(time, SWIGTYPE_p_Pool__Ball__Type.getCPtr(b), ShotParams.getCPtr(params), params), true);
  }

  public Event.Type getType() {
    return Event.Type.swigToEnum(fastfizJNI.CueStrikeEvent_getType(swigCPtr, this));
  }

  public String getTypeString() {
    return fastfizJNI.CueStrikeEvent_getTypeString(swigCPtr, this);
  }

  public ShotParams getParams() {
    return new ShotParams(fastfizJNI.CueStrikeEvent_getParams(swigCPtr, this), false);
  }

}
