/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public final class Decision {
  public final static Decision DEC_NO_DECISION = new Decision("DEC_NO_DECISION");
  public final static Decision DEC_KEEP_SHOOTING = new Decision("DEC_KEEP_SHOOTING");
  public final static Decision DEC_RERACK = new Decision("DEC_RERACK");
  public final static Decision DEC_EIGHTBALL_RERACK_OPP_SHOOT = new Decision("DEC_EIGHTBALL_RERACK_OPP_SHOOT");
  public final static Decision DEC_CONCEDE = new Decision("DEC_CONCEDE");
  public final static Decision DEC_NINEBALL_PUSH_OUT = new Decision("DEC_NINEBALL_PUSH_OUT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Decision swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Decision.class + " with value " + swigValue);
  }

  private Decision(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Decision(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Decision(String swigName, Decision swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Decision[] swigValues = { DEC_NO_DECISION, DEC_KEEP_SHOOTING, DEC_RERACK, DEC_EIGHTBALL_RERACK_OPP_SHOOT, DEC_CONCEDE, DEC_NINEBALL_PUSH_OUT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

