/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public class fastfiz {
  public static StateChangeEvent eventToStateChangeEvent(Event event) {
    return new StateChangeEvent(fastfizJNI.eventToStateChangeEvent(Event.getCPtr(event), event), false);
  }

  public static BallCollisionEvent eventToBallCollisionEvent(Event event) {
    return new BallCollisionEvent(fastfizJNI.eventToBallCollisionEvent(Event.getCPtr(event), event), false);
  }

  public static RailCollisionEvent eventToRailCollisionEvent(Event event) {
    return new RailCollisionEvent(fastfizJNI.eventToRailCollisionEvent(Event.getCPtr(event), event), false);
  }

  public static PocketedEvent eventToPocketedEvent(Event event) {
    return new PocketedEvent(fastfizJNI.eventToPocketedEvent(Event.getCPtr(event), event), false);
  }

  public static CueStrikeEvent eventToCueStrikeEvent(Event event) {
    return new CueStrikeEvent(fastfizJNI.eventToCueStrikeEvent(Event.getCPtr(event), event), false);
  }

  public static String getFastFizVersion() {
    return fastfizJNI.getFastFizVersion();
  }

  public static TableState getTestState() {
    long cPtr = fastfizJNI.getTestState();
    return (cPtr == 0) ? null : new TableState(cPtr, true);
  }

  public static ShotParams getTestShotParams() {
    long cPtr = fastfizJNI.getTestShotParams();
    return (cPtr == 0) ? null : new ShotParams(cPtr, true);
  }

  public static String getRulesVersion() {
    return fastfizJNI.getRulesVersion();
  }

}
