/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public final class GameType {
  public final static GameType GT_NONE = new GameType("GT_NONE");
  public final static GameType GT_EIGHTBALL = new GameType("GT_EIGHTBALL");
  public final static GameType GT_NINEBALL = new GameType("GT_NINEBALL");
  public final static GameType GT_SNOOKER = new GameType("GT_SNOOKER");
  public final static GameType GT_ONEPOCKET = new GameType("GT_ONEPOCKET");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GameType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GameType.class + " with value " + swigValue);
  }

  private GameType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GameType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GameType(String swigName, GameType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GameType[] swigValues = { GT_NONE, GT_EIGHTBALL, GT_NINEBALL, GT_SNOOKER, GT_ONEPOCKET };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

