/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public final class NoiseType {
  public final static NoiseType NT_UNDEFINED = new NoiseType("NT_UNDEFINED");
  public final static NoiseType NT_NONE = new NoiseType("NT_NONE");
  public final static NoiseType NT_GAUSSIAN = new NoiseType("NT_GAUSSIAN", fastfizJNI.NT_GAUSSIAN_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NoiseType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NoiseType.class + " with value " + swigValue);
  }

  private NoiseType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NoiseType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NoiseType(String swigName, NoiseType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NoiseType[] swigValues = { NT_UNDEFINED, NT_NONE, NT_GAUSSIAN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

