/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public class Noise {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Noise(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Noise obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Noise obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fastfizJNI.delete_Noise(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Noise Factory(String sourceString) {
    long cPtr = fastfizJNI.Noise_Factory(sourceString);
    return (cPtr == 0) ? null : new Noise(cPtr, false);
  }

  public String toString() {
    return fastfizJNI.Noise_toString(swigCPtr, this);
  }

  public NoiseType noiseType() {
    return NoiseType.swigToEnum(fastfizJNI.Noise_noiseType(swigCPtr, this));
  }

  public void applyNoise(ShotParams sp) {
    fastfizJNI.Noise_applyNoise(swigCPtr, this, ShotParams.getCPtr(sp), sp);
  }

}
