/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public class NoNoise extends Noise {
  private transient long swigCPtr;

  protected NoNoise(long cPtr, boolean cMemoryOwn) {
    super(fastfizJNI.NoNoise_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NoNoise obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(NoNoise obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fastfizJNI.delete_NoNoise(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NoNoise() {
    this(fastfizJNI.new_NoNoise__SWIG_0(), true);
  }

  public NoNoise(SWIGTYPE_p_std__istream sourceStream) {
    this(fastfizJNI.new_NoNoise__SWIG_1(SWIGTYPE_p_std__istream.getCPtr(sourceStream)), true);
  }

  public NoNoise(String noiseString) {
    this(fastfizJNI.new_NoNoise__SWIG_2(noiseString), true);
  }

  public NoiseType noiseType() {
    return NoiseType.swigToEnum(fastfizJNI.NoNoise_noiseType(swigCPtr, this));
  }

  public void applyNoise(ShotParams sp) {
    fastfizJNI.NoNoise_applyNoise(swigCPtr, this, ShotParams.getCPtr(sp), sp);
  }

}
