/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public class PocketedEvent extends Event {
  private transient long swigCPtr;

  protected PocketedEvent(long cPtr, boolean cMemoryOwn) {
    super(fastfizJNI.PocketedEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PocketedEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(PocketedEvent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fastfizJNI.delete_PocketedEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PocketedEvent(double time, Ball.Type b, Table.Pocket pocket) {
    this(fastfizJNI.new_PocketedEvent(time, b.swigValue(), pocket.swigValue()), true);
  }

  public Event.Type getType() {
    return Event.Type.swigToEnum(fastfizJNI.PocketedEvent_getType(swigCPtr, this));
  }

  public String getTypeString() {
    return fastfizJNI.PocketedEvent_getTypeString(swigCPtr, this);
  }

  public Table.Pocket getPocket() {
    return Table.Pocket.swigToEnum(fastfizJNI.PocketedEvent_getPocket(swigCPtr, this));
  }

}
