/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public class Point {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Point(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Point obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fastfizJNI.delete_Point(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(double value) {
    fastfizJNI.Point_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return fastfizJNI.Point_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    fastfizJNI.Point_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return fastfizJNI.Point_y_get(swigCPtr, this);
  }

  public Point() {
    this(fastfizJNI.new_Point__SWIG_0(), true);
  }

  public Point(double xx, double yy) {
    this(fastfizJNI.new_Point__SWIG_1(xx, yy), true);
  }

  public Point(Point rhs) {
    this(fastfizJNI.new_Point__SWIG_2(Point.getCPtr(rhs), rhs), true);
  }

  public String toString() {
    return fastfizJNI.Point_toString(swigCPtr, this);
  }

  public void fromString(String s) {
    fastfizJNI.Point_fromString(swigCPtr, this, s);
  }

}
