/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public class RealTimeStopwatch extends TimevalStopwatch {
  private transient long swigCPtr;

  protected RealTimeStopwatch(long cPtr, boolean cMemoryOwn) {
    super(fastfizJNI.RealTimeStopwatch_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RealTimeStopwatch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RealTimeStopwatch obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fastfizJNI.delete_RealTimeStopwatch(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Stopwatch create() {
    long cPtr = fastfizJNI.RealTimeStopwatch_create(swigCPtr, this);
    return (cPtr == 0) ? null : new Stopwatch(cPtr, false);
  }

  public RealTimeStopwatch() {
    this(fastfizJNI.new_RealTimeStopwatch(), true);
  }

}
