/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public class ShotParams {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ShotParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ShotParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ShotParams obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fastfizJNI.delete_ShotParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setA(double value) {
    fastfizJNI.ShotParams_a_set(swigCPtr, this, value);
  }

  public double getA() {
    return fastfizJNI.ShotParams_a_get(swigCPtr, this);
  }

  public void setB(double value) {
    fastfizJNI.ShotParams_b_set(swigCPtr, this, value);
  }

  public double getB() {
    return fastfizJNI.ShotParams_b_get(swigCPtr, this);
  }

  public void setTheta(double value) {
    fastfizJNI.ShotParams_theta_set(swigCPtr, this, value);
  }

  public double getTheta() {
    return fastfizJNI.ShotParams_theta_get(swigCPtr, this);
  }

  public void setPhi(double value) {
    fastfizJNI.ShotParams_phi_set(swigCPtr, this, value);
  }

  public double getPhi() {
    return fastfizJNI.ShotParams_phi_get(swigCPtr, this);
  }

  public void setV(double value) {
    fastfizJNI.ShotParams_v_set(swigCPtr, this, value);
  }

  public double getV() {
    return fastfizJNI.ShotParams_v_get(swigCPtr, this);
  }

  public ShotParams() {
    this(fastfizJNI.new_ShotParams__SWIG_0(), true);
  }

  public ShotParams(double _a, double _b, double _theta, double _phi, double _v) {
    this(fastfizJNI.new_ShotParams__SWIG_1(_a, _b, _theta, _phi, _v), true);
  }

  public ShotParams(ShotParams rhs) {
    this(fastfizJNI.new_ShotParams__SWIG_2(ShotParams.getCPtr(rhs), rhs), true);
  }

}
