/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public class Stopwatch {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Stopwatch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Stopwatch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Stopwatch obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fastfizJNI.delete_Stopwatch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void clear() {
    fastfizJNI.Stopwatch_clear(swigCPtr, this);
  }

  public void restart() {
    fastfizJNI.Stopwatch_restart(swigCPtr, this);
  }

  public double getElapsed() {
    return fastfizJNI.Stopwatch_getElapsed(swigCPtr, this);
  }

  public void stop() {
    fastfizJNI.Stopwatch_stop(swigCPtr, this);
  }

  public void start() {
    fastfizJNI.Stopwatch_start(swigCPtr, this);
  }

  public Stopwatch create() {
    long cPtr = fastfizJNI.Stopwatch_create(swigCPtr, this);
    return (cPtr == 0) ? null : new Stopwatch(cPtr, false);
  }

}
