/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public final class TurnType {
  public final static TurnType TT_NORMAL = new TurnType("TT_NORMAL");
  public final static TurnType TT_BALL_IN_HAND = new TurnType("TT_BALL_IN_HAND");
  public final static TurnType TT_BEHIND_LINE = new TurnType("TT_BEHIND_LINE");
  public final static TurnType TT_RESERVED = new TurnType("TT_RESERVED");
  public final static TurnType TT_BREAK = new TurnType("TT_BREAK");
  public final static TurnType TT_WIN = new TurnType("TT_WIN");
  public final static TurnType TT_EIGHTBALL_FOUL_ON_BREAK = new TurnType("TT_EIGHTBALL_FOUL_ON_BREAK");
  public final static TurnType TT_EIGHTBALL_8BALL_POCKETED_ON_BREAK = new TurnType("TT_EIGHTBALL_8BALL_POCKETED_ON_BREAK");
  public final static TurnType TT_NINEBALL_FIRST_SHOT = new TurnType("TT_NINEBALL_FIRST_SHOT");
  public final static TurnType TT_NINEBALL_PUSH_OUT = new TurnType("TT_NINEBALL_PUSH_OUT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TurnType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TurnType.class + " with value " + swigValue);
  }

  private TurnType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TurnType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TurnType(String swigName, TurnType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TurnType[] swigValues = { TT_NORMAL, TT_BALL_IN_HAND, TT_BEHIND_LINE, TT_RESERVED, TT_BREAK, TT_WIN, TT_EIGHTBALL_FOUL_ON_BREAK, TT_EIGHTBALL_8BALL_POCKETED_ON_BREAK, TT_NINEBALL_FIRST_SHOT, TT_NINEBALL_PUSH_OUT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

