/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package JFastfiz;

public class Vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Vector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fastfizJNI.delete_Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(double value) {
    fastfizJNI.Vector_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return fastfizJNI.Vector_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    fastfizJNI.Vector_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return fastfizJNI.Vector_y_get(swigCPtr, this);
  }

  public void setZ(double value) {
    fastfizJNI.Vector_z_set(swigCPtr, this, value);
  }

  public double getZ() {
    return fastfizJNI.Vector_z_get(swigCPtr, this);
  }

  public Vector() {
    this(fastfizJNI.new_Vector__SWIG_0(), true);
  }

  public Vector(double xx, double yy, double zz) {
    this(fastfizJNI.new_Vector__SWIG_1(xx, yy, zz), true);
  }

  public Vector(Vector rhs) {
    this(fastfizJNI.new_Vector__SWIG_2(Vector.getCPtr(rhs), rhs), true);
  }

  public String toString() {
    return fastfizJNI.Vector_toString(swigCPtr, this);
  }

  public void fromString(String s) {
    fastfizJNI.Vector_fromString(swigCPtr, this, s);
  }

}
